title: LavaLens - writing playground
name: Octavian Aarden
email: octavian.aarden@lavalens.com
description: I have gained an increasing interest in storytelling in recent years. Movies, novels and even poetry fuel my imagination with the potential they have to influence others. No other medium is a close to translating toughts from one person to another as the written word and more recently the moving pictures. I write movie reviews with a focus on European film, short stories and toughts.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b, %Y"

twitter_username: OctavianAarden
github_username: OctavianAarden

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
